// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func AgregarSimulacion() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<form class=\"form\" hx-target=\"#contenido\" hx-swap=\"innerHTML\" hx-post=\"/simulaciones\"><fieldset><legend>Nueva simulacion</legend> <label for=\"nombre\">Nombre de la simulacion</label> <input type=\"text\" name=\"nombre\" id=\"nombre\" placeholder=\"Nombre de la simulacion\"><p>Nota: De momento esta solamente implementado el First come First Serve, FCFS</p><label for=\"algoritmo\">Elegir el algoritmo de planificacion</label> <select id=\"algoritmo\" name=\"algoritmo\" hx-get=\"/algoritmo/opciones\" hx-target=\"#opciones-extra\" hx-trigger=\"change\" hx-swap=\"innerHTML\"><option value=\"first_come_first_serve\">First come First Serve</option> <option value=\"round_robin\">Round Robin</option> <option value=\"priority\">Prioridad</option> <option value=\"shortest_job_first\">Shortest Job First sin desalojo</option> <option value=\"shortest_job_first_preemptive\">Shortest Job First con desalojo</option></select><div id=\"opciones-extra\"></div><button type=\"submit\" class=\"button\">Enviar</button></fieldset></form>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
