// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func CrearGrafo() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section id=\"grafo\"><section class=\"card-container\"><article class=\"card\"><header class=\"card-header\"><h3>New</h3></header><footer class=\"card-footer\"><ul><li><a href=\"procesos_nuevos\" class=\"button\">Ver más</a></li></ul></footer></article><div class=\"ready-vs-waiting\"><article class=\"card\"><header class=\"card-header\"><h3>Ready</h3></header><footer class=\"card-footer\"><ul><li><a href=\"procesos_listos\" class=\"button\">Ver más</a></li></ul></footer></article><article class=\"card\"><header class=\"card-header\"><h3>Waiting</h3></header><footer class=\"card-footer\"><ul><li><a href=\"procesos_en_espera\" class=\"button\">Ver más</a></li></ul></footer></article></div><article class=\"card\"><header class=\"card-header\"><h3>Running</h3></header><footer class=\"card-footer\"><ul><li><a href=\"procesos_en_ejecucion\" class=\"button\">Ver más</a></li></ul></footer></article><article class=\"card\"><header class=\"card-header\"><h3>Terminated</h3></header><footer class=\"card-footer\"><ul><li><a href=\"procesos_terminados\" class=\"button\">Ver más</a></li></ul></footer></article></section><section class=\"start-section\"><a href=\"ejecutar_simulacion\" class=\"button\" id=\"comenzar\">Comenzar</a></section></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
