// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

type Proceso struct {
	ID           int32  `json:"id"`
	Nombre       string `json:"nombre"`
	Prioridad    int32  `json:"prioridad"`
	BurstTime    int32  `json:"burst_time"`
	ArrivalTime  int32  `json:"arrival_time"`
	Estado       string `json:"estado"`
	IDSimulacion int32  `json:"id_simulacion"`
}
