// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960

package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func AgregarForm() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<html><body><section><form action=\"/api/procesos\" method=\"POST\"><fieldset><legend>Crear proceso</legend> <label for=\"nombre\">Nombre</label> <input name=\"nombre\" id=\"nombre\" type=\"text\" placeholder=\"Ingrese el nombre del proceso\"> <label for=\"prioridad\">Prioridad</label> <input type=\"number\" name=\"prioridad\" id=\"prioridad\" placeholder=\"Ingrese la prioridad del proceso\"> <label for=\"burst_time\">Burst Time</label> <input type=\"number\" name=\"burst_time\" id=\"burst_time\" placeholder=\"Ingrese el burst time del proceso\" required> <label for=\"arrival_time\">Arrival time</label> <input type=\"number\" name=\"arrival_time\" id=\"arrival_time\" placeholder=\"Ingrese el arrival time del proceso\" required> <button type=\"submit\">Enviar</button></fieldset></form></section></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
